SRC =startup.fth util.fth asm.fth 
SRC += timer.fth  
SRC += gx1-cpu.fth 
SRC += gx1-scratchpad.fth 
SRC += pci.fth cs5530.fth
SRC += pnp.fth 
SRC += gx1-display.fth 
SRC += gx1-gaccel.fth
SRC += nvram.fth
SRC += memory.fth 
SRC += font8x16.fth
SRC += font4x6.fth
SRC += doc.fth
SRC += ide.fth
SRC += keyboard.fth
SRC += graphics.fth
SRC += chbuf.fth
SRC += disasm.fth
SRC += diag.fth
SRC += dwnldr.fth

all : $(SRC)
	cat $(SRC) > all.fth

