# tcpip stack from J bowman

SRCS=natsem.fth    # hardware defines 

SRCS += arp.fth
SRCS += ip.fth
#udp.fth
#SRCS += dhcp.fth
#SRCS += spi.fth
## SRCS += flash.fth
## SRCS += mt9v.fth
## SRCS += wge.fth
#SRCS += newtcp.fth
#SRCS += html.fth
#SRCS += http.fth
#SRCS += tcpservice.fth
#SRCS += ntp.fth
#SRCS += syslog.fth


all: ${SRCS} ${MSD}
	cat ${SRCS} > tcpip.fth



